### ISSUE TITLE
Broken MSI

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#354]
On Windows 10, tried to install over previous p2p installation by Launcher and got this while installing the MSI:

![capture](https://user-images.githubusercontent.com/10051386/30552653-8c81173a-9cc0-11e7-9f54-d420c251e9f7.PNG)

**Comment by crioto** [comment]
MSI itself isn't broken, but this is a result of service being installed by other application. This will gone after we update launchers, because now they don't count the fact that component may be installed by something else. This one can be closed, because launchers already modified to workaround this and fixed will be available on next dev update.

**Comment by akarasulu** [comment]
mike [12:19 PM] 
So after launcher release you can test


[12:19] 
Sure, this is not p2p issue, but launcher


akarasulu [12:19 PM] 
launchers will fix then this will work right ?


[12:20] 
meaning run of launchers when corrected will make this issue go away


mike [12:20 PM] 
Yes. Basically the problem was launcher installs service manager and p2p installs service manager and they start conflict. You remember about side effect I told you? We have changed default path on windows, where launcher will install components for subutai, so it will be properly handled by MSI too
