### ISSUE TITLE
[SPIKE] Global network positioning and distance between peers

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#445]
We need to improve our network tomography using global network positioning of peers. We need to better assess a peer's viability to join an environment swarm after the peer passes user governance criteria to reduce the candidate space. A system that is peer-to-peer friendly is needed. I've found this research paper and some code demonstrating it:

https://www.cs.rice.edu/~eugeneng/papers/INFOCOM02.pdf
https://www.cs.rice.edu/~eugeneng/research/gnp/
https://www.cs.rice.edu/~eugeneng/research/gnp/software.html

I don't know if this technique is the state of the art or other better ways (specifically for p2p) have emerged since then. It looks old, having been devised in 2002. We should check to see if there were advances.

It would also be nice to find an existing golang based library to efficiently estimate distances between peers.

**Comment by crioto** [comment]
During my research of possible solutions for network distance calculations I've come to the following conclusion:
Algorithms like Vivaldi and some others of the same kind are not suitable, because our current p2p network is being
truly peer to peer, except situation when we are connected over proxies. So the whole map will contain maximum of two hops:
* peer -> peer
* peer -> proxy -> peer
This is because these Algorithms in fact use relative network position. 

So one reasonable solution for us right now is to use latency as a measurement of the network distance between peers/proxies.
After implementation we could draw a basic star scheme by indicating latency values using line length (the longer line is, the 
higher latency value in ms.)
Later we can refactor/review this approach.

**Comment by crioto** [comment]
We've implemented latency based positioning of peers. For the next steps of global swarming and embedded proxies I will create new issues.

**Comment by kurmanbekova6** [comment]
```All Endpoints: 31.192.255.109:57565 [205]
> All Endpoints: 31.192.255.109:40842 [204] 85.25.210.145:20008 [206] 85.93.89.182:20036 [220]```
Fixed in  master

**Comment by kurmanbekova6** [comment]
```All Endpoints: 62.138.16.147:54285 [112] 85.93.91.135:20017 [108] ```
```All Endpoints: 62.138.16.147:55582 [110] 85.93.91.135:20121 [114] ```
Tested in master

**Comment by kurmanbekova6** [comment]
```All Endpoints: 62.138.16.147:34780 [102]
All Endpoints: 62.138.16.147:36298 [97] 85.93.91.135:20094 [103] 62.138.0.66:20143 [100] ```
Tested in prod
