### ISSUE TITLE
P2p works unstable on windows 10

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/p2p#505]
1. I installed it after several attempts, it couldn't be installed and was shown this error message:
![image](https://user-images.githubusercontent.com/34295807/34400903-41a06578-ebc0-11e7-81f8-cff1f181e682.png)
2. I created env with mate-Desktop template, buttons "SSH" and"EZ-Desktop" weren't clickable. After I started to collect logs, for it I stoped p2p on services list, then in cmd wrote command p2p daemon.  After this all buttons became clickable and worked properly: 
![image](https://user-images.githubusercontent.com/34295807/34400972-1c811d90-ebc1-11e7-8ab6-b4e606f177e6.png)
3. After I created another env. on USA peer, it started work also! 
4. I created 3 env on another  peer. After it weren't working, after some perion it started to work again (p2p isn't running in services)
[p2p.txt](https://github.com/subutai-io/p2p/files/1590586/p2p.txt)

Here I collect logs and some nessesary information.

**Comment by ibragim13kz** [comment]
![screenshot_1](https://user-images.githubusercontent.com/33474101/34434283-36c1ff96-ecaf-11e7-8a39-defc6588083c.png)
![screenshot_2](https://user-images.githubusercontent.com/33474101/34434284-372ec2b6-ecaf-11e7-8d60-ee147539df21.png)
![screenshot_3](https://user-images.githubusercontent.com/33474101/34434285-3790490a-ecaf-11e7-91bd-142846d6becd.png)
![screenshot_4](https://user-images.githubusercontent.com/33474101/34434286-37f7b662-ecaf-11e7-8399-d4d57d9f1676.png)
![screenshot_5](https://user-images.githubusercontent.com/33474101/34434287-387876da-ecaf-11e7-8998-d362531b73bc.png)

**Comment by ibragim13kz** [comment]
Logs: 

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\ProgramData\subutai\bin

C:\ProgramData\subutai\bin>p2p show
[ERROR] 2017/12/29 14:52:40 Failed to connect to RPC dial tcp [::1]:52523: connectex: No connection could be made because the target machine actively refused it.

C:\ProgramData\subutai\bin>p2p -v
p2p version 6.2.5

C:\ProgramData\subutai\bin>p2p debug
[ERROR] 2017/12/29 14:54:31 Failed to connect to RPC dial tcp [::1]:52523: connectex: No connection could be made because the target machine actively refused it.

C:\ProgramData\subutai\bin>
------------------------------------------------------------------------------------------------------------------- 
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\ProgramData\subutai\bin

C:\ProgramData\subutai\bin>p2p daemon
[WARNING] 2017/12/29 15:01:21 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:21 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:21 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:21 AdapterName : Ethernet 11, len : 11
[INFO] 2017/12/29 15:01:21 Acquired control over TAP interface: Ethernet 11
[INFO] 2017/12/29 15:01:21 Executing: netsh interface ip set address "Ethernet 11" static 172.0.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:22 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 3, len : 10
[INFO] 2017/12/29 15:01:22 Acquired control over TAP interface: Ethernet 3
[INFO] 2017/12/29 15:01:22 Executing: netsh interface ip set address "Ethernet 3" static 172.1.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:22 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:22 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 10, len : 11
[INFO] 2017/12/29 15:01:22 Acquired control over TAP interface: Ethernet 10
[INFO] 2017/12/29 15:01:22 Executing: netsh interface ip set address "Ethernet 10" static 172.2.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:22 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 10, len : 11
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 6, len : 24
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 9, len : 24
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 7, len : 10
[INFO] 2017/12/29 15:01:22 Acquired control over TAP interface: Ethernet 7
[INFO] 2017/12/29 15:01:22 Executing: netsh interface ip set address "Ethernet 7" static 172.3.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:22 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 10, len : 11
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 6, len : 24
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Local Area Connection* 9, len : 24
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 7, len : 10
[WARNING] 2017/12/29 15:01:22 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:22 AdapterName : Ethernet 9, len : 10
[INFO] 2017/12/29 15:01:22 Acquired control over TAP interface: Ethernet 9
[INFO] 2017/12/29 15:01:22 Executing: netsh interface ip set address "Ethernet 9" static 172.4.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:23 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 10, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 6, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 9, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 7, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 9, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 5, len : 24
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 8, len : 10
[INFO] 2017/12/29 15:01:23 Acquired control over TAP interface: Ethernet 8
[INFO] 2017/12/29 15:01:23 Executing: netsh interface ip set address "Ethernet 8" static 172.5.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:23 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 10, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 6, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 9, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 7, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 9, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 5, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 8, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 4, len : 10
[INFO] 2017/12/29 15:01:23 Acquired control over TAP interface: Ethernet 4
[INFO] 2017/12/29 15:01:23 Executing: netsh interface ip set address "Ethernet 4" static 172.6.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:23 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 10, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 6, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 9, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 7, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 9, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 5, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 8, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 4, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 4, len : 24
[WARNING] 2017/12/29 15:01:23 AdapterName : VirtualBox Host-Only Network, len : 28
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 5, len : 10
[INFO] 2017/12/29 15:01:23 Acquired control over TAP interface: Ethernet 5
[INFO] 2017/12/29 15:01:23 Executing: netsh interface ip set address "Ethernet 5" static 172.7.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:23 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 10, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 6, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 9, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 7, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 9, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 5, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 8, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 4, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 4, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : VirtualBox Host-Only Network, len : 28
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 5, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 8, len : 24
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 2, len : 24
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 2, len : 10
[INFO] 2017/12/29 15:01:23 Acquired control over TAP interface: Ethernet 2
[INFO] 2017/12/29 15:01:23 Executing: netsh interface ip set address "Ethernet 2" static 172.8.4.100 255.255.255.0
[WARNING] 2017/12/29 15:01:23 AdapterName : Bluetooth Network Connection, len : 28
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet (Kernel Debugger), len : 26
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 7, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 11, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 3, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Teredo Tunneling Pseudo-Interface, len : 33
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Wi-Fi, len : 5
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 10, len : 11
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 6, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 9, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 7, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 9, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 5, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 8, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 4, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 4, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : VirtualBox Host-Only Network, len : 28
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 5, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 8, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 2, len : 24
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 2, len : 10
[WARNING] 2017/12/29 15:01:23 Adapter already in use. Skipping.
[WARNING] 2017/12/29 15:01:23 AdapterName : Local Area Connection* 1, len : 24
[WARNING] 2017/12/29 15:01:23 AdapterName : Ethernet 6, len : 10
[INFO] 2017/12/29 15:01:23 Acquired control over TAP interface: Ethernet 6
[INFO] 2017/12/29 15:01:23 Executing: netsh interface ip set address "Ethernet 6" static 172.9.4.100 255.255.255.0
[INFO] 2017/12/29 15:01:23 Determining outbound IP
2017/12/29 15:01:33 method Initialize has wrong number of ins: 2
[INFO] 2017/12/29 15:01:33 Starting RPC Listener on 52523 port
-------------------------------------------------------------------------------------------------------------------
Environment info: 
[
  {
    "environment_ttl": 3600,
    "environment_key": "fad52c127e72de9fa4ae245aa3a11e9a",
    "environment_id": "9762b75e-2c4b-4e62-b11a-b408a00a16f5",
    "environment_status_desc": "Environment is ready",
    "environment_status": "HEALTHY",
    "environment_name": "IbraUbuntuProd",
    "environment_hash": "swarm-9762b75e-2c4b-4e62-b11a-b408a00a16f5",
    "environment_containers": [
      {
        "container_ip": "172.21.104.3",
        "container_is_desktop": "false",
        "container_name": "Container-1-bBQ",
        "rh_ip": "10.252.201.1",
        "container_id": "D7F4B5A5A7897B7BF735D8DD9955B78FC84B1EF4"
      }
    ]
  }
] 
------------------------------------------------------------------

**Comment by AlinaPenkina** [comment]
Fixed
